package study.RedisFlowControl.mybatis.model;

public class Esb2FlowCtrl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.controlid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String controlid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.channelid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.serviceid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String serviceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.tokentotalquantity
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String tokentotalquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.inmultidate
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String inmultidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.indate
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String indate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.inweek
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String inweek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.inmonth
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String inmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esb2_flow_ctrl.inyear
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    private String inyear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.controlid
     *
     * @return the value of esb2_flow_ctrl.controlid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getControlid() {
        return controlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.controlid
     *
     * @param controlid the value for esb2_flow_ctrl.controlid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setControlid(String controlid) {
        this.controlid = controlid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.channelid
     *
     * @return the value of esb2_flow_ctrl.channelid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.channelid
     *
     * @param channelid the value for esb2_flow_ctrl.channelid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.serviceid
     *
     * @return the value of esb2_flow_ctrl.serviceid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.serviceid
     *
     * @param serviceid the value for esb2_flow_ctrl.serviceid
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setServiceid(String serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.tokentotalquantity
     *
     * @return the value of esb2_flow_ctrl.tokentotalquantity
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getTokentotalquantity() {
        return tokentotalquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.tokentotalquantity
     *
     * @param tokentotalquantity the value for esb2_flow_ctrl.tokentotalquantity
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setTokentotalquantity(String tokentotalquantity) {
        this.tokentotalquantity = tokentotalquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.inmultidate
     *
     * @return the value of esb2_flow_ctrl.inmultidate
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getInmultidate() {
        return inmultidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.inmultidate
     *
     * @param inmultidate the value for esb2_flow_ctrl.inmultidate
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setInmultidate(String inmultidate) {
        this.inmultidate = inmultidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.indate
     *
     * @return the value of esb2_flow_ctrl.indate
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getIndate() {
        return indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.indate
     *
     * @param indate the value for esb2_flow_ctrl.indate
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setIndate(String indate) {
        this.indate = indate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.inweek
     *
     * @return the value of esb2_flow_ctrl.inweek
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getInweek() {
        return inweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.inweek
     *
     * @param inweek the value for esb2_flow_ctrl.inweek
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setInweek(String inweek) {
        this.inweek = inweek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.inmonth
     *
     * @return the value of esb2_flow_ctrl.inmonth
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getInmonth() {
        return inmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.inmonth
     *
     * @param inmonth the value for esb2_flow_ctrl.inmonth
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setInmonth(String inmonth) {
        this.inmonth = inmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esb2_flow_ctrl.inyear
     *
     * @return the value of esb2_flow_ctrl.inyear
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getInyear() {
        return inyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esb2_flow_ctrl.inyear
     *
     * @param inyear the value for esb2_flow_ctrl.inyear
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setInyear(String inyear) {
        this.inyear = inyear;
    }
}