package test.model;

import java.util.ArrayList;
import java.util.List;

public class Esb2FlowCtrlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public Esb2FlowCtrlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andControlidIsNull() {
            addCriterion("controlid is null");
            return (Criteria) this;
        }

        public Criteria andControlidIsNotNull() {
            addCriterion("controlid is not null");
            return (Criteria) this;
        }

        public Criteria andControlidEqualTo(String value) {
            addCriterion("controlid =", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidNotEqualTo(String value) {
            addCriterion("controlid <>", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidGreaterThan(String value) {
            addCriterion("controlid >", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidGreaterThanOrEqualTo(String value) {
            addCriterion("controlid >=", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidLessThan(String value) {
            addCriterion("controlid <", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidLessThanOrEqualTo(String value) {
            addCriterion("controlid <=", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidLike(String value) {
            addCriterion("controlid like", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidNotLike(String value) {
            addCriterion("controlid not like", value, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidIn(List<String> values) {
            addCriterion("controlid in", values, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidNotIn(List<String> values) {
            addCriterion("controlid not in", values, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidBetween(String value1, String value2) {
            addCriterion("controlid between", value1, value2, "controlid");
            return (Criteria) this;
        }

        public Criteria andControlidNotBetween(String value1, String value2) {
            addCriterion("controlid not between", value1, value2, "controlid");
            return (Criteria) this;
        }

        public Criteria andChannelidIsNull() {
            addCriterion("channelid is null");
            return (Criteria) this;
        }

        public Criteria andChannelidIsNotNull() {
            addCriterion("channelid is not null");
            return (Criteria) this;
        }

        public Criteria andChannelidEqualTo(String value) {
            addCriterion("channelid =", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotEqualTo(String value) {
            addCriterion("channelid <>", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidGreaterThan(String value) {
            addCriterion("channelid >", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidGreaterThanOrEqualTo(String value) {
            addCriterion("channelid >=", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidLessThan(String value) {
            addCriterion("channelid <", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidLessThanOrEqualTo(String value) {
            addCriterion("channelid <=", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidLike(String value) {
            addCriterion("channelid like", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotLike(String value) {
            addCriterion("channelid not like", value, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidIn(List<String> values) {
            addCriterion("channelid in", values, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotIn(List<String> values) {
            addCriterion("channelid not in", values, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidBetween(String value1, String value2) {
            addCriterion("channelid between", value1, value2, "channelid");
            return (Criteria) this;
        }

        public Criteria andChannelidNotBetween(String value1, String value2) {
            addCriterion("channelid not between", value1, value2, "channelid");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNull() {
            addCriterion("serviceid is null");
            return (Criteria) this;
        }

        public Criteria andServiceidIsNotNull() {
            addCriterion("serviceid is not null");
            return (Criteria) this;
        }

        public Criteria andServiceidEqualTo(String value) {
            addCriterion("serviceid =", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotEqualTo(String value) {
            addCriterion("serviceid <>", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThan(String value) {
            addCriterion("serviceid >", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidGreaterThanOrEqualTo(String value) {
            addCriterion("serviceid >=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThan(String value) {
            addCriterion("serviceid <", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLessThanOrEqualTo(String value) {
            addCriterion("serviceid <=", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidLike(String value) {
            addCriterion("serviceid like", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotLike(String value) {
            addCriterion("serviceid not like", value, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidIn(List<String> values) {
            addCriterion("serviceid in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotIn(List<String> values) {
            addCriterion("serviceid not in", values, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidBetween(String value1, String value2) {
            addCriterion("serviceid between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andServiceidNotBetween(String value1, String value2) {
            addCriterion("serviceid not between", value1, value2, "serviceid");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityIsNull() {
            addCriterion("tokentotalquantity is null");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityIsNotNull() {
            addCriterion("tokentotalquantity is not null");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityEqualTo(String value) {
            addCriterion("tokentotalquantity =", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityNotEqualTo(String value) {
            addCriterion("tokentotalquantity <>", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityGreaterThan(String value) {
            addCriterion("tokentotalquantity >", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityGreaterThanOrEqualTo(String value) {
            addCriterion("tokentotalquantity >=", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityLessThan(String value) {
            addCriterion("tokentotalquantity <", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityLessThanOrEqualTo(String value) {
            addCriterion("tokentotalquantity <=", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityLike(String value) {
            addCriterion("tokentotalquantity like", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityNotLike(String value) {
            addCriterion("tokentotalquantity not like", value, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityIn(List<String> values) {
            addCriterion("tokentotalquantity in", values, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityNotIn(List<String> values) {
            addCriterion("tokentotalquantity not in", values, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityBetween(String value1, String value2) {
            addCriterion("tokentotalquantity between", value1, value2, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andTokentotalquantityNotBetween(String value1, String value2) {
            addCriterion("tokentotalquantity not between", value1, value2, "tokentotalquantity");
            return (Criteria) this;
        }

        public Criteria andInmultidateIsNull() {
            addCriterion("inmultidate is null");
            return (Criteria) this;
        }

        public Criteria andInmultidateIsNotNull() {
            addCriterion("inmultidate is not null");
            return (Criteria) this;
        }

        public Criteria andInmultidateEqualTo(String value) {
            addCriterion("inmultidate =", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateNotEqualTo(String value) {
            addCriterion("inmultidate <>", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateGreaterThan(String value) {
            addCriterion("inmultidate >", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateGreaterThanOrEqualTo(String value) {
            addCriterion("inmultidate >=", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateLessThan(String value) {
            addCriterion("inmultidate <", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateLessThanOrEqualTo(String value) {
            addCriterion("inmultidate <=", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateLike(String value) {
            addCriterion("inmultidate like", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateNotLike(String value) {
            addCriterion("inmultidate not like", value, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateIn(List<String> values) {
            addCriterion("inmultidate in", values, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateNotIn(List<String> values) {
            addCriterion("inmultidate not in", values, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateBetween(String value1, String value2) {
            addCriterion("inmultidate between", value1, value2, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andInmultidateNotBetween(String value1, String value2) {
            addCriterion("inmultidate not between", value1, value2, "inmultidate");
            return (Criteria) this;
        }

        public Criteria andIndateIsNull() {
            addCriterion("indate is null");
            return (Criteria) this;
        }

        public Criteria andIndateIsNotNull() {
            addCriterion("indate is not null");
            return (Criteria) this;
        }

        public Criteria andIndateEqualTo(String value) {
            addCriterion("indate =", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotEqualTo(String value) {
            addCriterion("indate <>", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateGreaterThan(String value) {
            addCriterion("indate >", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateGreaterThanOrEqualTo(String value) {
            addCriterion("indate >=", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateLessThan(String value) {
            addCriterion("indate <", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateLessThanOrEqualTo(String value) {
            addCriterion("indate <=", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateLike(String value) {
            addCriterion("indate like", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotLike(String value) {
            addCriterion("indate not like", value, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateIn(List<String> values) {
            addCriterion("indate in", values, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotIn(List<String> values) {
            addCriterion("indate not in", values, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateBetween(String value1, String value2) {
            addCriterion("indate between", value1, value2, "indate");
            return (Criteria) this;
        }

        public Criteria andIndateNotBetween(String value1, String value2) {
            addCriterion("indate not between", value1, value2, "indate");
            return (Criteria) this;
        }

        public Criteria andInweekIsNull() {
            addCriterion("inweek is null");
            return (Criteria) this;
        }

        public Criteria andInweekIsNotNull() {
            addCriterion("inweek is not null");
            return (Criteria) this;
        }

        public Criteria andInweekEqualTo(String value) {
            addCriterion("inweek =", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekNotEqualTo(String value) {
            addCriterion("inweek <>", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekGreaterThan(String value) {
            addCriterion("inweek >", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekGreaterThanOrEqualTo(String value) {
            addCriterion("inweek >=", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekLessThan(String value) {
            addCriterion("inweek <", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekLessThanOrEqualTo(String value) {
            addCriterion("inweek <=", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekLike(String value) {
            addCriterion("inweek like", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekNotLike(String value) {
            addCriterion("inweek not like", value, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekIn(List<String> values) {
            addCriterion("inweek in", values, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekNotIn(List<String> values) {
            addCriterion("inweek not in", values, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekBetween(String value1, String value2) {
            addCriterion("inweek between", value1, value2, "inweek");
            return (Criteria) this;
        }

        public Criteria andInweekNotBetween(String value1, String value2) {
            addCriterion("inweek not between", value1, value2, "inweek");
            return (Criteria) this;
        }

        public Criteria andInmonthIsNull() {
            addCriterion("inmonth is null");
            return (Criteria) this;
        }

        public Criteria andInmonthIsNotNull() {
            addCriterion("inmonth is not null");
            return (Criteria) this;
        }

        public Criteria andInmonthEqualTo(String value) {
            addCriterion("inmonth =", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthNotEqualTo(String value) {
            addCriterion("inmonth <>", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthGreaterThan(String value) {
            addCriterion("inmonth >", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthGreaterThanOrEqualTo(String value) {
            addCriterion("inmonth >=", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthLessThan(String value) {
            addCriterion("inmonth <", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthLessThanOrEqualTo(String value) {
            addCriterion("inmonth <=", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthLike(String value) {
            addCriterion("inmonth like", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthNotLike(String value) {
            addCriterion("inmonth not like", value, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthIn(List<String> values) {
            addCriterion("inmonth in", values, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthNotIn(List<String> values) {
            addCriterion("inmonth not in", values, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthBetween(String value1, String value2) {
            addCriterion("inmonth between", value1, value2, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInmonthNotBetween(String value1, String value2) {
            addCriterion("inmonth not between", value1, value2, "inmonth");
            return (Criteria) this;
        }

        public Criteria andInyearIsNull() {
            addCriterion("inyear is null");
            return (Criteria) this;
        }

        public Criteria andInyearIsNotNull() {
            addCriterion("inyear is not null");
            return (Criteria) this;
        }

        public Criteria andInyearEqualTo(String value) {
            addCriterion("inyear =", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotEqualTo(String value) {
            addCriterion("inyear <>", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearGreaterThan(String value) {
            addCriterion("inyear >", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearGreaterThanOrEqualTo(String value) {
            addCriterion("inyear >=", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearLessThan(String value) {
            addCriterion("inyear <", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearLessThanOrEqualTo(String value) {
            addCriterion("inyear <=", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearLike(String value) {
            addCriterion("inyear like", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotLike(String value) {
            addCriterion("inyear not like", value, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearIn(List<String> values) {
            addCriterion("inyear in", values, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotIn(List<String> values) {
            addCriterion("inyear not in", values, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearBetween(String value1, String value2) {
            addCriterion("inyear between", value1, value2, "inyear");
            return (Criteria) this;
        }

        public Criteria andInyearNotBetween(String value1, String value2) {
            addCriterion("inyear not between", value1, value2, "inyear");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated do_not_delete_during_merge Thu Dec 20 10:10:52 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}