package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Esb2FlowCtrl;
import test.model.Esb2FlowCtrlExample;

public interface Esb2FlowCtrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int countByExample(Esb2FlowCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int deleteByExample(Esb2FlowCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int deleteByPrimaryKey(String controlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int insert(Esb2FlowCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int insertSelective(Esb2FlowCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    List<Esb2FlowCtrl> selectByExample(Esb2FlowCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    Esb2FlowCtrl selectByPrimaryKey(String controlid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") Esb2FlowCtrl record, @Param("example") Esb2FlowCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int updateByExample(@Param("record") Esb2FlowCtrl record, @Param("example") Esb2FlowCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int updateByPrimaryKeySelective(Esb2FlowCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esb2_flow_ctrl
     *
     * @mbggenerated Thu Dec 20 10:10:52 CST 2018
     */
    int updateByPrimaryKey(Esb2FlowCtrl record);
}