package domain;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.birthday
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mail
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nation
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.married
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    private Integer married;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.birthday
     *
     * @return the value of users.birthday
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.birthday
     *
     * @param birthday the value for users.birthday
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mail
     *
     * @return the value of users.mail
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mail
     *
     * @param mail the value for users.mail
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile
     *
     * @return the value of users.mobile
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile
     *
     * @param mobile the value for users.mobile
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nation
     *
     * @return the value of users.nation
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nation
     *
     * @param nation the value for users.nation
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.married
     *
     * @return the value of users.married
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public Integer getMarried() {
        return married;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.married
     *
     * @param married the value for users.married
     *
     * @mbggenerated Mon Aug 27 11:01:17 CST 2018
     */
    public void setMarried(Integer married) {
        this.married = married;
    }
}