insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('AST', 'all', '500', '', '', '', '', '', '100');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NLCPT', 'all', '500', '', '', '', '', '', '101');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NYTALK', 'all', '500', '', '', '', '', '', '88');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('QPAY', 'all', '500', '', '', '', '', '', '92');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('MAS', 'all', '500', '', '', '', '', '', '48');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('WACS', 'all', '500', '', '', '', '', '', '49');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ATMP', 'all', '500', '', '', '', '', '', '52');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('TSMP', 'all', '500', '', '', '', '', '', '62');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('MSAP', 'all', '500', '', '', '', '', '', '63');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('all', '1000330018801', '2', '', '', '', '', '', 'd8ce2377-09eb-4373-baed-484b561a2c65');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('all', '1000130003101', '2', '', '', '', '', '', '82363e4a-fbaa-422d-bd06-802b9040a411');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ECMS', 'all', '500', '', '', '', '', '', '76');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SDSS', 'all', '500', '', '', '', '', '', '77');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('RMS', 'all', '500', '', '', '', '', '', '78');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('MABS', 'all', '500', '', '', '', '', '', '80');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('OIS', 'all', '500', '', '', '', '', '', '89');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('BTCP', 'all', '500', '', '', '', '', '', '90');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('AMLS', 'all', '500', '', '', '', '', '', '47');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SENT', 'all', '500', '', '', '', '', '', '57');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CISCQ', 'all', '500', '', '', '', '', '', '66');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EMS', 'all', '500', '', '', '', '', '', '68');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('VCS', 'all', '500', '', '', '', '', '', '83');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SZFS', 'all', '500', '', '', '', '', '', '4');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CMIS', 'all', '500', '', '', '', '', '', '15');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('AGENT', 'all', '500', '', '', '', '', '', '11');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ZJGL', 'all', '500', '', '', '', '', '', '23');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ZZZJ', 'all', '500', '', '', '', '', '', '25');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('RPEB', 'all', '500', '', '', '', '', '', '31');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('PBS', 'all', '500', '', '', '', '', '', '27');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('PAM', 'all', '500', '', '', '', '', '', '40');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EONE', 'all', '500', '', '', '', '', '', '41');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ECTIP', 'all', '500', '', '', '', '', '', '46');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CNAPS2', 'all', '500', '', '', '', '', '', '1');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('RURALBANK', 'all', '500', '', '', '', '', '', '2');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ESAS', 'all', '500', '', '', '', '', '', '3');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('HRM', 'all', '500', '', '', '', '', '', '6');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('OA', 'all', '500', '', '', '', '', '', '7');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EBANK', 'all', '500', '', '', '', '', '', '5');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('LCPT', 'all', '500', '', '', '', '', '', '8');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EBANK_HTTP', 'all', '500', '', '', '', '', '', '12');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('VPN', 'all', '500', '', '', '', '', '', '10');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CIS', 'all', '500', '', '', '', '', '', '24');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('TELLER', 'all', '500', '', '', '', '', '', '19');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NEWAGENT', 'all', '500', '', '', '', '', '', '20');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ODS', 'all', '500', '', '', '', '', '', '32');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('RCEB', 'all', '500', '', '', '', '', '', '82609e52-ba2f-4a0e-bc0f-0976d7981ca9');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SCF', 'all', '500', '', '', '', '', '', '42');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ATMV', 'all', '500', '', '', '', '', '', '9');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('MBS', 'all', '500', '', '', '', '', '', '13');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('AGENT(MBS)', 'all', '500', '', '', '', '', '', '14');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NEWCORE2', 'all', '500', '', '', '', '', '', '29');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EBLS', 'all', '500', '', '', '', '', '', '30');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EPBANK', 'all', '500', '', '', '', '', '', '38');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('MBANK', 'all', '500', '', '', '', '', '', '28');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('HSACS', 'all', '500', '', '', '', '', '', '44');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CORE', 'all', '500', '', '', '', '', '', '17');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ZHWD', 'all', '500', '', '', '', '', '', '16');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('PDJ', 'all', '500', '', '', '', '', '', '18');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('PAYMENT', 'all', '500', '', '', '', '', '', '21');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('AGENT', 'all', '500', '', '', '', '', '', '22');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('WBANK', 'all', '500', '', '', '', '', '', '26');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('FIN', 'all', '500', '', '', '', '', '', '33');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CDS', 'all', '500', '', '', '', '', '', '43');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('WEBSITE', 'all', '500', '', '', '', '', '', '45');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('IBRANCH', 'all', '500', '', '', '', '', '', '50');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CSGL', 'all', '500', '', '', '', '', '', '53');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ATMP_NEW', 'all', '500', '', '', '', '', '', '54');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('BST', 'all', '500', '', '', '', '', '', '58');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('POSP', 'all', '500', '', '', '', '', '', '59');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('OA_NEW', 'all', '500', '', '', '', '', '', '60');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CRM', 'all', '500', '', '', '', '', '', '61');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NUPCS', 'all', '500', '', '', '', '', '', '91');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('EKPEXT', 'all', '500', '', '', '', '', '', '93');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NEWSMS', 'all', '500', '', '', '', '', '', '51');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ICS', 'all', '500', '', '', '', '', '', '55');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('OCWEB', 'all', '500', '', '', '', '', '', '56');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('WBKPS', 'all', '500', '', '', '', '', '', '64');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('PMS', 'all', '500', '', '', '', '', '', '65');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ESS', 'all', '500', '', '', '', '', '', '67');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('UPL', 'all', '500', '', '', '', '', '', '69');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('YQDZ', 'all', '500', '', '', '', '', '', '70');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('WHZJ', 'all', '500', '', '', '', '', '', '71');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('DQMP', 'all', '500', '', '', '', '', '', '72');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('HJDL', 'all', '500', '', '', '', '', '', '37');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SOP', 'all', '500', '', '', '', '', '', '73');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('all', '1000230015201', '2', '', '', '', '', '', '249544e9-604f-4d87-8f32-490e8d2981fc');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('all', '1000130003001', '2', '', '', '', '', '', '2293f8f6-ac61-4904-b42c-febca1e596d8');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('all', '1000130003002', '2', '', '', '', '', '', 'de1beb50-6fa2-40b2-82a0-ac535db7eb64');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('all', '1000130003003', '2', '', '', '', '', '', '024b80ac-451d-4d66-a616-031620e1a1e5');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SMP', 'all', '500', '', '', '', '', '', '74');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('NYBANKNM', 'all', '500', '', '', '', '', '', '75');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('HCE', 'all', '500', '', '', '', '', '', '81');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('ECIF', 'all', '500', '', '', '', '', '', '82');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('RWBANK', 'all', '500', '', '', '', '', '', '79');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CREDIT', 'all', '500', '', '', '', '', '', '84');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SOCIALBANK', 'all', '500', '', '', '', '', '', '85');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('DCMS', 'all', '500', '', '', '', '', '', '86');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('UPRR', 'all', '500', '', '', '', '', '', '87');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('MOBILEKEY', 'all', '500', '', '', '', '', '', '94');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SASS', 'all', '500', '', '', '', '', '', '95');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('SMART', 'all', '500', '', '', '', '', '', '96');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('IDS', 'all', '500', '', '', '', '', '', '97');

insert into ESB2_FLOW_CTRL (CHANNELID, SERVICEID, TOKENTOTALQUANTITY, INMULTIDATE, INDATE, INWEEK, INMONTH, INYEAR, CONTROLID)
values ('CCMS', 'all', '500', '', '', '', '', '', '99');

